# Generated by Django 5.2.6 on 2025-11-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inse',
            fields=[
                ('id', models.PositiveIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('email', models.CharField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
